//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.28 at 05:10:27 PM ART 
//


package co.com.directv.sdii.dto.esb.event.publishworkorderevent;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MovementCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MovementCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Value1"/>
 *     &lt;enumeration value="Value2"/>
 *     &lt;enumeration value="Value3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MovementCategory")
@XmlEnum
public enum MovementCategory {

    @XmlEnumValue("Value1")
    VALUE_1("Value1"),
    @XmlEnumValue("Value2")
    VALUE_2("Value2"),
    @XmlEnumValue("Value3")
    VALUE_3("Value3");
    private final String value;

    MovementCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MovementCategory fromValue(String v) {
        for (MovementCategory c: MovementCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
