//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.07 at 10:11:01 AM ART 
//


package co.com.directv.sdii.dto.esb.dispatchtechnician;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReceiveMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReceiveMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_Priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="_UseCaseData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="_XMLDoc" type="{http://directvla.com/schema/util/commondatatypes/v2-0}DataArea"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReceiveMessage", namespace = "http://directvla.com/schema/util/commondatatypes/v2-0", propOrder = {
    "priority",
    "useCaseData",
    "xmlDoc"
})
public class ReceiveMessage
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "_Priority")
    protected String priority;
    @XmlElement(name = "_UseCaseData", required = true, nillable = true)
    protected String useCaseData;
    @XmlElement(name = "_XMLDoc", required = true, nillable = true)
    protected DataArea xmlDoc;

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the useCaseData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseCaseData() {
        return useCaseData;
    }

    /**
     * Sets the value of the useCaseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseCaseData(String value) {
        this.useCaseData = value;
    }

    /**
     * Gets the value of the xmlDoc property.
     * 
     * @return
     *     possible object is
     *     {@link DataArea }
     *     
     */
    public DataArea getXMLDoc() {
        return xmlDoc;
    }

    /**
     * Sets the value of the xmlDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataArea }
     *     
     */
    public void setXMLDoc(DataArea value) {
        this.xmlDoc = value;
    }

}
