//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.07 at 10:11:01 AM ART 
//


package co.com.directv.sdii.dto.esb.dispatchtechnician;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WithdrawWorkOrderFromTechnicianResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WithdrawWorkOrderFromTechnicianResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WorkOrderResultCollection" type="{http://directvla.com/contract/businessdomain/EventListener/v1-0}WorkOrderResultCollection"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WithdrawWorkOrderFromTechnicianResult", namespace = "http://directvla.com/contract/businessdomain/EventListener/v1-0", propOrder = {
    "workOrderResultCollection"
})
public class WithdrawWorkOrderFromTechnicianResult
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "WorkOrderResultCollection", required = true)
    protected WorkOrderResultCollection workOrderResultCollection;

    /**
     * Gets the value of the workOrderResultCollection property.
     * 
     * @return
     *     possible object is
     *     {@link WorkOrderResultCollection }
     *     
     */
    public WorkOrderResultCollection getWorkOrderResultCollection() {
        return workOrderResultCollection;
    }

    /**
     * Sets the value of the workOrderResultCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkOrderResultCollection }
     *     
     */
    public void setWorkOrderResultCollection(WorkOrderResultCollection value) {
        this.workOrderResultCollection = value;
    }

}
