//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.07 at 10:11:01 AM ART 
//


package co.com.directv.sdii.dto.esb.dispatchtechnician;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestMetadata" type="{http://directvla.com/schema/util/commondatatypes/v2-0}RequestMetadataType"/>
 *         &lt;element name="WithdrawWorkOrderFromTechnician" type="{http://directvla.com/contract/businessdomain/EventListener/v1-0}WithdrawWorkOrderFromTechnician"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestMetadata",
    "withdrawWorkOrderFromTechnician"
})
@XmlRootElement(name = "WithdrawWorkOrderFromTechnicianRequest", namespace = "http://directvla.com/contract/businessdomain/EventListener/v1-0")
public class WithdrawWorkOrderFromTechnicianRequest
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "RequestMetadata", namespace = "http://directvla.com/contract/businessdomain/EventListener/v1-0", required = true)
    protected RequestMetadataType requestMetadata;
    @XmlElement(name = "WithdrawWorkOrderFromTechnician", namespace = "http://directvla.com/contract/businessdomain/EventListener/v1-0", required = true)
    protected WithdrawWorkOrderFromTechnician withdrawWorkOrderFromTechnician;

    /**
     * Gets the value of the requestMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link RequestMetadataType }
     *     
     */
    public RequestMetadataType getRequestMetadata() {
        return requestMetadata;
    }

    /**
     * Sets the value of the requestMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestMetadataType }
     *     
     */
    public void setRequestMetadata(RequestMetadataType value) {
        this.requestMetadata = value;
    }

    /**
     * Gets the value of the withdrawWorkOrderFromTechnician property.
     * 
     * @return
     *     possible object is
     *     {@link WithdrawWorkOrderFromTechnician }
     *     
     */
    public WithdrawWorkOrderFromTechnician getWithdrawWorkOrderFromTechnician() {
        return withdrawWorkOrderFromTechnician;
    }

    /**
     * Sets the value of the withdrawWorkOrderFromTechnician property.
     * 
     * @param value
     *     allowed object is
     *     {@link WithdrawWorkOrderFromTechnician }
     *     
     */
    public void setWithdrawWorkOrderFromTechnician(WithdrawWorkOrderFromTechnician value) {
        this.withdrawWorkOrderFromTechnician = value;
    }

}
