//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.07 at 10:11:01 AM ART 
//


package co.com.directv.sdii.dto.esb.dispatchtechnician;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="responseMetadata" type="{http://directvla.com/schema/util/commondatatypes/v2-0}ResponseMetadataType"/>
 *         &lt;element name="WithdrawWorkOrderFromTechnicianResult" type="{http://directvla.com/contract/businessdomain/EventListener/v1-0}WithdrawWorkOrderFromTechnicianResult"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseMetadata",
    "withdrawWorkOrderFromTechnicianResult"
})
@XmlRootElement(name = "WithdrawWorkOrderFromTechnicianResponse", namespace = "http://directvla.com/contract/businessdomain/EventListener/v1-0")
public class WithdrawWorkOrderFromTechnicianResponse
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(namespace = "http://directvla.com/contract/businessdomain/EventListener/v1-0", required = true)
    protected ResponseMetadataType responseMetadata;
    @XmlElement(name = "WithdrawWorkOrderFromTechnicianResult", namespace = "http://directvla.com/contract/businessdomain/EventListener/v1-0", required = true)
    protected WithdrawWorkOrderFromTechnicianResult withdrawWorkOrderFromTechnicianResult;

    /**
     * Gets the value of the responseMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMetadataType }
     *     
     */
    public ResponseMetadataType getResponseMetadata() {
        return responseMetadata;
    }

    /**
     * Sets the value of the responseMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMetadataType }
     *     
     */
    public void setResponseMetadata(ResponseMetadataType value) {
        this.responseMetadata = value;
    }

    /**
     * Gets the value of the withdrawWorkOrderFromTechnicianResult property.
     * 
     * @return
     *     possible object is
     *     {@link WithdrawWorkOrderFromTechnicianResult }
     *     
     */
    public WithdrawWorkOrderFromTechnicianResult getWithdrawWorkOrderFromTechnicianResult() {
        return withdrawWorkOrderFromTechnicianResult;
    }

    /**
     * Sets the value of the withdrawWorkOrderFromTechnicianResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link WithdrawWorkOrderFromTechnicianResult }
     *     
     */
    public void setWithdrawWorkOrderFromTechnicianResult(WithdrawWorkOrderFromTechnicianResult value) {
        this.withdrawWorkOrderFromTechnicianResult = value;
    }

}
