ALTER SESSION SET CURRENT_SCHEMA={{schema}};

DROP INDEX {{schema}}.CREW_MODIFICATIONS_IDX01;
DROP TABLE {{schema}}.CREW_MODIFICATIONS;
DROP SEQUENCE  {{schema}}.SEQ_CREW_MODIFICATIONS;

DROP INDEX {{schema}}.WO_CREW_ATTENTIONS_IDX01;
DROP TABLE {{schema}}.WORK_ORDER_CREW_ATTENTIONS;
DROP SEQUENCE  {{schema}}.SEQ_WORK_ORDER_CREW_ATTENTIONS;

DROP INDEX {{schema}}.ADJUSTMENT_ELEMENTS_IDX01;
DROP INDEX {{schema}}.WAREHOUSE_ELEMENTS_IDX13;

commit;