//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 10:51:09 AM ART 
//


package co.com.directv.sdii.dto.esb.notifyWorkOrdersOptimus;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeographicArea complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeographicArea">
 *   &lt;complexContent>
 *     &lt;extension base="{http://directvla.com/schema/businessdomain/common/v1-0}GeographicLocation">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="City" type="{http://directvla.com/schema/businessdomain/common/v1-0}City" minOccurs="0"/>
 *         &lt;element name="Country" type="{http://directvla.com/schema/businessdomain/common/v1-0}Country" minOccurs="0"/>
 *         &lt;element name="State" type="{http://directvla.com/schema/businessdomain/common/v1-0}State" minOccurs="0"/>
 *         &lt;element name="Province" type="{http://directvla.com/schema/businessdomain/common/v1-0}Province" minOccurs="0"/>
 *         &lt;element name="PostCode" type="{http://directvla.com/schema/businessdomain/common/v1-0}GeographicPostcode" minOccurs="0"/>
 *         &lt;element name="PostCodeTo" type="{http://directvla.com/schema/businessdomain/common/v1-0}GeographicPostcode" minOccurs="0"/>
 *         &lt;element name="smallCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HouseNumberAlphaFrom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HouseNumberAlphaTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HouseNumberFrom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HouseNumberTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Exclusive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeographicArea", propOrder = {
    "id",
    "name",
    "code",
    "type",
    "city",
    "country",
    "state",
    "province",
    "postCode",
    "postCodeTo",
    "smallCity",
    "houseNumberAlphaFrom",
    "houseNumberAlphaTo",
    "houseNumberFrom",
    "houseNumberTo",
    "exclusive"
})
public class GeographicArea
    extends GeographicLocation
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected Integer id;
    protected String name;
    protected String code;
    protected String type;
    @XmlElement(name = "City")
    protected City city;
    @XmlElement(name = "Country")
    protected Country country;
    @XmlElement(name = "State")
    protected State state;
    @XmlElement(name = "Province")
    protected Province province;
    @XmlElement(name = "PostCode")
    protected GeographicPostcode postCode;
    @XmlElement(name = "PostCodeTo")
    protected GeographicPostcode postCodeTo;
    protected String smallCity;
    @XmlElement(name = "HouseNumberAlphaFrom")
    protected String houseNumberAlphaFrom;
    @XmlElement(name = "HouseNumberAlphaTo")
    protected String houseNumberAlphaTo;
    @XmlElement(name = "HouseNumberFrom")
    protected String houseNumberFrom;
    @XmlElement(name = "HouseNumberTo")
    protected String houseNumberTo;
    @XmlElement(name = "Exclusive")
    protected Boolean exclusive;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link City }
     *     
     */
    public City getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link City }
     *     
     */
    public void setCity(City value) {
        this.city = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setCountry(Country value) {
        this.country = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link State }
     *     
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link State }
     *     
     */
    public void setState(State value) {
        this.state = value;
    }

    /**
     * Gets the value of the province property.
     * 
     * @return
     *     possible object is
     *     {@link Province }
     *     
     */
    public Province getProvince() {
        return province;
    }

    /**
     * Sets the value of the province property.
     * 
     * @param value
     *     allowed object is
     *     {@link Province }
     *     
     */
    public void setProvince(Province value) {
        this.province = value;
    }

    /**
     * Gets the value of the postCode property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicPostcode }
     *     
     */
    public GeographicPostcode getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicPostcode }
     *     
     */
    public void setPostCode(GeographicPostcode value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the postCodeTo property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicPostcode }
     *     
     */
    public GeographicPostcode getPostCodeTo() {
        return postCodeTo;
    }

    /**
     * Sets the value of the postCodeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicPostcode }
     *     
     */
    public void setPostCodeTo(GeographicPostcode value) {
        this.postCodeTo = value;
    }

    /**
     * Gets the value of the smallCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmallCity() {
        return smallCity;
    }

    /**
     * Sets the value of the smallCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmallCity(String value) {
        this.smallCity = value;
    }

    /**
     * Gets the value of the houseNumberAlphaFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseNumberAlphaFrom() {
        return houseNumberAlphaFrom;
    }

    /**
     * Sets the value of the houseNumberAlphaFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseNumberAlphaFrom(String value) {
        this.houseNumberAlphaFrom = value;
    }

    /**
     * Gets the value of the houseNumberAlphaTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseNumberAlphaTo() {
        return houseNumberAlphaTo;
    }

    /**
     * Sets the value of the houseNumberAlphaTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseNumberAlphaTo(String value) {
        this.houseNumberAlphaTo = value;
    }

    /**
     * Gets the value of the houseNumberFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseNumberFrom() {
        return houseNumberFrom;
    }

    /**
     * Sets the value of the houseNumberFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseNumberFrom(String value) {
        this.houseNumberFrom = value;
    }

    /**
     * Gets the value of the houseNumberTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseNumberTo() {
        return houseNumberTo;
    }

    /**
     * Sets the value of the houseNumberTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseNumberTo(String value) {
        this.houseNumberTo = value;
    }

    /**
     * Gets the value of the exclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExclusive() {
        return exclusive;
    }

    /**
     * Sets the value of the exclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExclusive(Boolean value) {
        this.exclusive = value;
    }

}
