//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 10:51:09 AM ART 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://directvla.com/schema/businessdomain/common/v1-0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.com.directv.sdii.dto.esb.notifyWorkOrdersOptimus;
